# Generated by Django 5.2.8 on 2026-07-05 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('total_asientos', models.IntegerField(default=4, help_text='Capacidad total del auto')),
                ('tiene_cajuela', models.BooleanField(default=True)),
                ('sketchfab_model_id', models.CharField(help_text='ID hash del modelo 3D en Sketchfab (Ej: 0f2f3579ea374c4caea9d20c78a0bb99)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('chofer', 'Chofer')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(help_text='Nombre del grupo (ej: Grupo A)', max_length=20)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15)),
            ],
            options={
                'verbose_name': 'Día de Rol',
                'verbose_name_plural': 'Roles por Día',
                'unique_together': {('grupo', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activo', 'Activo / Libre (Aceptando viajes particulares)'), ('en_ruta', 'En Ruta Fija (Día de Rol)'), ('inactivo', 'Inactivo / Fuera de Servicio')], default='pendiente', max_length=20)),
                ('grupo_rol', models.CharField(blank=True, help_text='Grupo asignado, ej: Grupo A, Grupo B', max_length=20, null=True)),
                ('asientos_disponibles', models.IntegerField(default=4, help_text='Asientos libres en tiempo real durante la ruta')),
                ('latitud', models.FloatField(default=0.0)),
                ('longitud', models.FloatField(default=0.0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chofer_datos', to='Taxis.perfilusuario')),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer_actual', to='Taxis.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_lat', models.FloatField()),
                ('origen_lng', models.FloatField()),
                ('origen_direccion', models.CharField(blank=True, help_text='Texto amigable del origen', max_length=255)),
                ('destino_lat', models.FloatField()),
                ('destino_lng', models.FloatField()),
                ('destino_direccion', models.CharField(blank=True, help_text='Texto amigable del destino', max_length=255)),
                ('asientos_solicitados', models.IntegerField(default=1)),
                ('requiere_cajuela', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('solicitado', 'Buscando Chofer más cercano'), ('aceptado', 'Chofer en camino al punto de subida'), ('en_curso', 'En camino al destino (Viajando)'), ('terminado', 'Viaje Concluido'), ('cancelado', 'Viaje Cancelado')], default='solicitado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, help_text='Evaluación del cliente al chofer (1 a 5 estrellas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_cliente', models.TextField(blank=True, null=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_atendidos', to='Taxis.chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_solicitados', to='Taxis.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Detalles de lo ocurrido')),
                ('nivel_emergencia', models.CharField(choices=[('bajo', 'Leve / Reporte general'), ('medio', 'Moderado / Retraso o altercado'), ('alto', 'CRÍTICO / SOS (Dispara alerta en Panel)')], default='bajo', max_length=10)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False, help_text='Marcar cuando el administrador atienda la situación')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_hechos', to='Taxis.perfilusuario')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='Taxis.viaje')),
            ],
        ),
    ]
