# Generated by Django 5.2.8 on 2026-07-05 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roldia',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='comentario_cliente',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(default='Temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(default='temporal@ejemplo.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default='temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password_hash',
            field=models.CharField(default='temporal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(default='temporal', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chofer',
            name='asientos_disponibles',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activo', 'Activo / Libre'), ('en_ruta', 'En Ruta Fija'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='grupo_rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roldia',
            name='dia_semana',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='roldia',
            name='grupo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='sketchfab_model_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='total_asientos',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Buscando Chofer'), ('aceptado', 'Chofer en camino'), ('en_curso', 'En viaje'), ('terminado', 'Viaje Concluido'), ('cancelado', 'Viaje Cancelado')], default='solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
    ]
