# Generated by Django 5.2.8 on 2026-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0003_alter_perfilusuario_options_remove_perfilusuario_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activo', 'Activo / Libre'), ('en_ruta', 'En Ruta Fija'), ('inactivo', 'Inactivo')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='latitud',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='longitud',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placas',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Buscando Chofer'), ('aceptado', 'Chofer en camino'), ('en_curso', 'En viaje'), ('terminado', 'Viaje Concluido'), ('cancelado', 'Viaje Cancelado')], db_index=True, default='solicitado', max_length=20),
        ),
    ]
