# Generated by Django 5.2.8 on 2026-08-03 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0005_base_parada_ruta_administradorbase_pago_rutaparada'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choferes', to='Taxis.base'),
        ),
    ]
