# Generated by Django 5.2.8 on 2026-08-04 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0006_chofer_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='calificacion',
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='Taxis.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Incomprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomprobante', to='Taxis.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion_viaje', 'Asignación de Viaje'), ('pago_rol', 'Pago de Rol'), ('calificacion', 'Nueva Calificación')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Taxis.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='PagoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pagado', max_length=20)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_rol', to='Taxis.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratado', 'Servicio Contratado'), ('paquete', 'Paquete Turístico'), ('personalizado', 'Personalizado')], default='contratado', max_length=20)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('finalizado', 'Finalizado')], default='solicitado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Taxis.chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_especiales', to='Taxis.perfilusuario')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje_especial', to='Taxis.pago')),
            ],
        ),
    ]
