# Generated by Django 5.2.8 on 2026-08-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0008_ruta_trazado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorol',
            name='liberado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_liberados', to='Taxis.perfilusuario'),
        ),
        migrations.AddField(
            model_name='pagorol',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagorol',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('pagado', 'Pagado / Liberado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
