# Generated by Django 5.2.8 on 2026-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxis', '0009_pagorol_liberado_por_pagorol_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='foto_licencia',
            field=models.ImageField(blank=True, null=True, upload_to='licencias/'),
        ),
    ]
